from content import C,LANGS,t
IDS=['one-bedroom','two-bedroom','two-bedroom-duplex','three-bedroom','three-bedroom-duplex','four-bedroom','four-bedroom-duplex','penthouse']
CATEGORY=[0,1,1,2,2,3,3,4]
IMAGES=[('living',2),('dining',3),('lounge',9),('bedroom',4),('living',2),('dining',3),('lounge',9),('architecture',1)]
t('typeNames',
['One-bedroom residence','Two-bedroom residence','Two-bedroom duplex','Three-bedroom residence','Three-bedroom duplex','Four-bedroom residence','Four-bedroom duplex','Penthouse'],
['Résidence 1 chambre','Résidence 2 chambres','Duplex 2 chambres','Résidence 3 chambres','Duplex 3 chambres','Résidence 4 chambres','Duplex 4 chambres','Penthouse'],
['Residencia de 1 dormitorio','Residencia de 2 dormitorios','Dúplex de 2 dormitorios','Residencia de 3 dormitorios','Dúplex de 3 dormitorios','Residencia de 4 dormitorios','Dúplex de 4 dormitorios','Ático'],
['Residentie met 1 slaapkamer','Residentie met 2 slaapkamers','Duplex met 2 slaapkamers','Residentie met 3 slaapkamers','Duplex met 3 slaapkamers','Residentie met 4 slaapkamers','Duplex met 4 slaapkamers','Penthouse'],
['Residenz mit 1 Schlafzimmer','Residenz mit 2 Schlafzimmern','Maisonette mit 2 Schlafzimmern','Residenz mit 3 Schlafzimmern','Maisonette mit 3 Schlafzimmern','Residenz mit 4 Schlafzimmern','Maisonette mit 4 Schlafzimmern','Penthouse'],
['Residência de 1 quarto','Residência de 2 quartos','Duplex de 2 quartos','Residência de 3 quartos','Duplex de 3 quartos','Residência de 4 quartos','Duplex de 4 quartos','Penthouse'])
t('typeSlugs',
['one-bedroom-apartment','two-bedroom-apartment','two-bedroom-duplex','three-bedroom-apartment','three-bedroom-duplex','four-bedroom-apartment','four-bedroom-duplex','penthouse'],
['appartement-1-chambre','appartement-2-chambres','duplex-2-chambres','appartement-3-chambres','duplex-3-chambres','appartement-4-chambres','duplex-4-chambres','penthouse'],
['apartamento-1-dormitorio','apartamento-2-dormitorios','duplex-2-dormitorios','apartamento-3-dormitorios','duplex-3-dormitorios','apartamento-4-dormitorios','duplex-4-dormitorios','atico'],
['appartement-1-slaapkamer','appartement-2-slaapkamers','duplex-2-slaapkamers','appartement-3-slaapkamers','duplex-3-slaapkamers','appartement-4-slaapkamers','duplex-4-slaapkamers','penthouse'],
['wohnung-1-schlafzimmer','wohnung-2-schlafzimmer','maisonette-2-schlafzimmer','wohnung-3-schlafzimmer','maisonette-3-schlafzimmer','wohnung-4-schlafzimmer','maisonette-4-schlafzimmer','penthouse'],
['apartamento-1-quarto','apartamento-2-quartos','duplex-2-quartos','apartamento-3-quartos','duplex-3-quartos','apartamento-4-quartos','duplex-4-quartos','penthouse'])
t('typeIntros',
['A one-bedroom address in The Ritz-Carlton collection on Al Maryah Island. Explore the entry category, the published starting price and the documents needed to compare individual homes.','Two bedrooms in a private branded residence on Al Maryah Island. Compare the apartment configuration with the separate two-bedroom duplex before selecting a specific home.','Two bedrooms in a duplex configuration within The Ritz-Carlton collection. A distinct alternative to the two-bedroom apartment, with the internal arrangement to confirm from the unit plan.','A three-bedroom option in the Al Maryah Island collection. Start with the apartment layout, then compare it with the three-bedroom duplex to understand which configuration suits your household.','The three-bedroom duplex combines this bedroom category with a duplex configuration. Request both levels of the floor plan to assess circulation and the relationship between shared and private rooms.','The four-bedroom residence is part of the larger-bedroom categories in the collection. Review the apartment plan alongside the four-bedroom duplex to assess your priorities for daily living.','A four-bedroom duplex in the private collection. Compare the layout across levels, access and room distribution with the four-bedroom apartment before choosing a unit.','The penthouse is a distinct category in the collection of 165 private homes. Request its dedicated specification: the brochure does not provide a confirmed bedroom count, area or asking price.'],
['Une adresse 1 chambre dans la collection Ritz-Carlton sur Al Maryah Island. Découvrez la catégorie d’entrée, son prix de départ et les documents utiles pour comparer les lots.','Deux chambres dans une résidence privée de marque sur Al Maryah Island. Comparez la configuration appartement avec le duplex 2 chambres avant de choisir un lot.','Deux chambres dans une configuration duplex au sein de la collection Ritz-Carlton. Une alternative à l’appartement 2 chambres, dont la distribution exacte doit être vérifiée sur le plan du lot.','Une option 3 chambres dans la collection d’Al Maryah Island. Examinez le plan de l’appartement puis comparez-le au duplex 3 chambres pour déterminer la configuration adaptée à votre foyer.','Le duplex 3 chambres associe cette catégorie de chambres à une organisation sur plusieurs niveaux. Demandez les plans de chaque niveau pour évaluer les circulations et la séparation entre pièces de vie et espaces privés.','La résidence 4 chambres fait partie des catégories comptant le plus de chambres dans la collection. Comparez son plan à celui du duplex 4 chambres pour définir vos priorités de vie quotidienne.','Un duplex 4 chambres dans la collection privée. Comparez l’accès, les circulations entre niveaux et la répartition des pièces avec l’appartement 4 chambres avant de choisir un lot.','Le penthouse est une catégorie distincte parmi les 165 résidences privées. Demandez sa fiche dédiée : la brochure ne confirme ni le nombre de chambres, ni la surface, ni le prix demandé.'],
['Una vivienda de un dormitorio en la colección Ritz-Carlton de Al Maryah Island. Explore la categoría de entrada, su precio inicial y los documentos para comparar unidades.','Dos dormitorios en una residencia privada de marca en Al Maryah Island. Compare la configuración de apartamento con el dúplex de dos dormitorios antes de elegir una unidad.','Dos dormitorios en configuración dúplex dentro de la colección Ritz-Carlton. Una alternativa al apartamento de dos dormitorios, cuya distribución debe confirmarse en el plano de la unidad.','Una opción de tres dormitorios en Al Maryah Island. Examine el plano del apartamento y compárelo con el dúplex de tres dormitorios para elegir la configuración adecuada para su hogar.','El dúplex de tres dormitorios combina esta categoría con una distribución en varios niveles. Solicite los planos de cada nivel para valorar la circulación y la relación entre zonas comunes y privadas.','La residencia de cuatro dormitorios forma parte de las categorías con más habitaciones de la colección. Compare su plano con el dúplex de cuatro dormitorios según sus prioridades cotidianas.','Un dúplex de cuatro dormitorios en la colección privada. Compare acceso, circulación entre niveles y distribución con el apartamento de cuatro dormitorios antes de elegir una unidad.','El ático es una categoría propia entre las 165 viviendas privadas. Solicite su ficha específica: el folleto no confirma dormitorios, superficie ni precio.'],
['Een woning met één slaapkamer in de Ritz-Carlton-collectie op Al Maryah Island. Ontdek de instapcategorie, de vanafprijs en de informatie om individuele woningen te vergelijken.','Twee slaapkamers in een privéresidentie op Al Maryah Island. Vergelijk de appartementindeling met de duplex met twee slaapkamers voordat u een woning kiest.','Twee slaapkamers in een duplexindeling binnen de Ritz-Carlton-collectie. Een alternatief voor het appartement met twee slaapkamers; de precieze indeling moet blijken uit de woningplattegrond.','Een optie met drie slaapkamers op Al Maryah Island. Bekijk de appartementplattegrond en vergelijk deze met de duplex met drie slaapkamers voor de indeling die bij uw huishouden past.','De duplex met drie slaapkamers combineert deze categorie met meerdere woonlagen. Vraag plattegronden van iedere laag om looproutes en de verdeling van gezamenlijke en privéruimtes te beoordelen.','De residentie met vier slaapkamers behoort tot de categorieën met meer slaapkamers in de collectie. Vergelijk het plan met de duplex met vier slaapkamers vanuit uw dagelijkse woonwensen.','Een duplex met vier slaapkamers in de privécollectie. Vergelijk toegang, looproutes tussen de woonlagen en de kamerindeling met het appartement met vier slaapkamers voordat u kiest.','Het penthouse is een aparte categorie binnen de 165 privéwoningen. Vraag de specifieke gegevens op: de brochure bevestigt geen aantal slaapkamers, oppervlakte of vraagprijs.'],
['Eine Residenz mit einem Schlafzimmer in der Ritz-Carlton-Kollektion auf Al Maryah Island. Entdecken Sie die Einstiegskategorie, den Ausgangspreis und die Unterlagen zum Vergleich einzelner Einheiten.','Zwei Schlafzimmer in einer privaten Markenresidenz auf Al Maryah Island. Vergleichen Sie die Wohnung mit der Maisonette mit zwei Schlafzimmern, bevor Sie eine Einheit auswählen.','Zwei Schlafzimmer als Maisonette in der Ritz-Carlton-Kollektion. Eine Alternative zur Wohnung mit zwei Schlafzimmern; die genaue Raumaufteilung ist anhand des Einheitengrundrisses zu bestätigen.','Eine Option mit drei Schlafzimmern auf Al Maryah Island. Prüfen Sie den Wohnungsgrundriss und vergleichen Sie ihn mit der Maisonette mit drei Schlafzimmern für Ihren Haushalt.','Die Maisonette mit drei Schlafzimmern verbindet diese Kategorie mit mehreren Wohnebenen. Fordern Sie die Pläne jeder Ebene an, um Wege und die Anordnung gemeinsamer und privater Räume zu beurteilen.','Die Residenz mit vier Schlafzimmern gehört zu den Kategorien mit mehr Schlafzimmern in der Kollektion. Vergleichen Sie den Grundriss mit der Maisonette mit vier Schlafzimmern anhand Ihrer Wohnwünsche.','Eine Maisonette mit vier Schlafzimmern in der privaten Kollektion. Vergleichen Sie Zugang, Wege zwischen den Ebenen und Raumaufteilung mit der Wohnung mit vier Schlafzimmern vor Ihrer Auswahl.','Das Penthouse ist eine eigene Kategorie unter den 165 privaten Residenzen. Fordern Sie die genaue Ausstattungsliste an: Die Broschüre bestätigt weder Schlafzimmerzahl noch Fläche oder Preis.'],
['Uma residência de um quarto na coleção Ritz-Carlton em Al Maryah Island. Explore a categoria de entrada, o preço inicial e os documentos necessários para comparar unidades.','Dois quartos numa residência privada de marca em Al Maryah Island. Compare a configuração de apartamento com o duplex de dois quartos antes de escolher uma unidade.','Dois quartos em configuração duplex na coleção Ritz-Carlton. Uma alternativa ao apartamento de dois quartos, cuja distribuição exata deve ser confirmada na planta da unidade.','Uma opção de três quartos em Al Maryah Island. Analise a planta do apartamento e compare com o duplex de três quartos para escolher a configuração adequada à sua família.','O duplex de três quartos combina esta categoria com vários níveis. Peça as plantas de cada nível para avaliar circulação e relação entre espaços comuns e privados.','A residência de quatro quartos integra as categorias com mais quartos da coleção. Compare a planta com o duplex de quatro quartos segundo as suas prioridades diárias.','Um duplex de quatro quartos na coleção privada. Compare acessos, circulação entre níveis e distribuição com o apartamento de quatro quartos antes de escolher.','A penthouse é uma categoria distinta entre as 165 residências privadas. Peça a especificação própria: a brochura não confirma número de quartos, área ou preço.'])
t('brochureCta','Get the brochure','Recevoir la brochure','Recibir el folleto','Brochure ontvangen','Broschüre erhalten','Receber a brochura')
t('brochureTitle','A closer look.<br>Your private collection.','Entrez dans les détails.<br>Votre collection privée.','Todos los detalles.<br>Su colección privada.','Een beter beeld.<br>Uw privécollectie.','Ein genauerer Blick.<br>Ihre private Kollektion.','Um olhar mais próximo.<br>A sua coleção privada.')
t('brochureIntro','Complete the form to access the project brochure in English. Your download link appears here after Tally confirms your submission.','Remplissez le formulaire pour accéder à la brochure du programme en anglais. Le lien de téléchargement s’affichera ici après confirmation de l’envoi par Tally.','Complete el formulario para acceder al folleto del proyecto en inglés. El enlace de descarga aparecerá aquí cuando Tally confirme el envío.','Vul het formulier in voor de projectbrochure in het Engels. De downloadlink verschijnt hier zodra Tally uw inzending bevestigt.','Füllen Sie das Formular aus, um die Projektbroschüre auf Englisch zu erhalten. Der Downloadlink erscheint hier, sobald Tally Ihre Übermittlung bestätigt.','Preencha o formulário para aceder à brochura do projeto em inglês. A ligação de download surge aqui quando o Tally confirmar o envio.')
t('brochureReady','Thank you. Your brochure is ready.','Merci. Votre brochure est prête.','Gracias. Su folleto está listo.','Bedankt. Uw brochure staat klaar.','Vielen Dank. Ihre Broschüre ist bereit.','Obrigado. A sua brochura está pronta.')
t('brochureDownload','Download the brochure · PDF','Télécharger la brochure · PDF','Descargar el folleto · PDF','Brochure downloaden · PDF','Broschüre herunterladen · PDF','Descarregar a brochura · PDF')
t('viewType','Explore this residence','Découvrir cette résidence','Ver esta residencia','Bekijk deze residentie','Diese Residenz entdecken','Explorar esta residência')
t('typeFacts','Your residence, in detail','Votre résidence, en détail','Su residencia, en detalle','Uw residentie in detail','Ihre Residenz im Detail','A sua residência em detalhe')
t('area','Internal area & terrace','Surface intérieure et terrasse','Superficie interior y terraza','Binnenoppervlakte en terras','Innenfläche und Terrasse','Área interior e terraço')
t('areaUnknown','Unit-specific plan required','Plan du lot à demander','Solicitar plano de la unidad','Plattegrond per woning opvragen','Grundriss der Einheit anfordern','Pedir planta da unidade')
t('illustrationType','Project imagery for illustration; not a verified representation of this specific residence type.','Visuels du programme à titre illustratif, non confirmés pour cette typologie précise.','Imágenes ilustrativas del proyecto; no verificadas para esta tipología concreta.','Projectbeelden ter illustratie; niet bevestigd voor dit specifieke woningtype.','Projektbilder zur Illustration; keine bestätigte Darstellung dieses konkreten Wohnungstyps.','Imagens ilustrativas do projeto; não confirmadas para esta tipologia específica.')
t('confirmTitle','What to confirm before reserving','À confirmer avant de réserver','Qué confirmar antes de reservar','Te bevestigen vóór reservering','Vor der Reservierung klären','O que confirmar antes de reservar')
t('confirmBody','Ask for the full unit plan, internal and external areas, floor, orientation, view and furnishing schedule. Review service charges, registration costs and the dated payment schedule with the unit-specific price.','Demandez le plan complet, les surfaces intérieures et extérieures, l’étage, l’orientation, la vue et la liste du mobilier. Vérifiez les charges, frais d’enregistrement et dates de paiement avec le prix du lot.','Solicite plano completo, superficies interiores y exteriores, planta, orientación, vistas y mobiliario. Revise gastos de comunidad, registro y fechas de pago junto al precio de la unidad.','Vraag het volledige plan, binnen- en buitenoppervlak, verdieping, oriëntatie, uitzicht en meubellijst op. Controleer servicekosten, registratiekosten en betaaldata met de prijs per woning.','Fordern Sie vollständigen Grundriss, Innen- und Außenflächen, Etage, Ausrichtung, Aussicht und Möbelliste an. Prüfen Sie Servicegebühren, Registrierungskosten und Zahlungstermine zusammen mit dem Einheitspreis.','Peça planta completa, áreas interiores e exteriores, piso, orientação, vista e mobiliário. Verifique condomínio, custos de registo e datas de pagamento juntamente com o preço da unidade.')
t('otherTypes','Explore the collection','Explorer la collection','Explorar la colección','Ontdek de collectie','Kollektion entdecken','Explorar a coleção')
t('typePriceUnknown','No confirmed starting price has been supplied for this specific type. Request a current unit offer; the one-bedroom starting price does not apply here.','Aucun prix de départ confirmé n’a été fourni pour cette typologie. Demandez une offre par lot ; le prix de départ 1 chambre ne s’applique pas ici.','No se ha facilitado un precio inicial confirmado para esta tipología. Solicite una oferta por unidad; el precio de un dormitorio no se aplica aquí.','Er is geen bevestigde vanafprijs voor dit type verstrekt. Vraag een offerte per woning; de vanafprijs voor één slaapkamer is hier niet van toepassing.','Für diesen Typ wurde kein bestätigter Einstiegspreis angegeben. Fordern Sie ein Angebot je Einheit an; der Preis für ein Schlafzimmer gilt hier nicht.','Não foi fornecido preço inicial confirmado para esta tipologia. Peça uma proposta por unidade; o preço inicial de um quarto não se aplica aqui.')
t('typePlanNote','The project brief specifies {booking}% on booking, {construction}% during construction and {handoverPart}% at handover. Monetary amounts for this type can only be calculated once its unit price is confirmed.','Le brief du programme prévoit {booking} % à la réservation, {construction} % pendant la construction et {handoverPart} % à la livraison. Les montants de cette typologie ne pourront être calculés qu’après confirmation du prix du lot.','El proyecto indica {booking} % en la reserva, {construction} % durante la construcción y {handoverPart} % en la entrega. Los importes de esta tipología solo pueden calcularse al confirmar el precio de la unidad.','Het project noemt {booking}% bij reservering, {construction}% tijdens de bouw en {handoverPart}% bij oplevering. Bedragen voor dit type kunnen pas na bevestiging van de woningprijs worden berekend.','Die Projektangaben nennen {booking} % bei Reservierung, {construction} % während der Bauphase und {handoverPart} % bei Übergabe. Beträge für diesen Typ lassen sich erst nach Bestätigung des Einheitspreises berechnen.','O projeto indica {booking}% na reserva, {construction}% durante a construção e {handoverPart}% na entrega. Os montantes desta tipologia só podem ser calculados após confirmação do preço da unidade.')
for l in LANGS:
 for i,id in enumerate(IDS):C[l][id]=f'/{l}/ritz-carlton-abu-dhabi/{C[l]["typeSlugs"][i]}/'
t('typeTitleSuffix','Prices & brochure','Prix et brochure','Precios y folleto','Prijzen en brochure','Preise und Broschüre','Preços e brochura')
